#include "EntryPoints.h"

#define DEFINE_GL_ENTRYPOINTS(Type,Func) Type Func = 0;
GL_ENTRYPOINTS_ALL(DEFINE_GL_ENTRYPOINTS);
#undef DEFINE_GL_ENTRYPOINTS

PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB = 0;