#ifndef ENTRY_POINTS_H
#define ENTRY_POINTS_H

#include <GL/glcorearb.h>
#include <GL/glext.h>
#include <GL/wglext.h>

#include <CoreMinimal.h>

#define GL_ENTRYPOINTS_DLL(EntryPoint) \
	EntryPoint(PFNGLBINDTEXTUREPROC,glBindTexture) \
	EntryPoint(PFNGLBLENDFUNCPROC,glBlendFunc) \
	EntryPoint(PFNGLCOLORMASKPROC,glColorMask) \
	EntryPoint(PFNGLCOPYTEXIMAGE1DPROC,glCopyTexImage1D) \
	EntryPoint(PFNGLCOPYTEXIMAGE2DPROC,glCopyTexImage2D) \
	EntryPoint(PFNGLCOPYTEXSUBIMAGE1DPROC,glCopyTexSubImage1D) \
	EntryPoint(PFNGLCOPYTEXSUBIMAGE2DPROC,glCopyTexSubImage2D) \
	EntryPoint(PFNGLCULLFACEPROC,glCullFace) \
	EntryPoint(PFNGLDELETETEXTURESPROC,glDeleteTextures) \
	EntryPoint(PFNGLDEPTHFUNCPROC,glDepthFunc) \
	EntryPoint(PFNGLDEPTHMASKPROC,glDepthMask) \
	EntryPoint(PFNGLDEPTHRANGEPROC,glDepthRange) \
	EntryPoint(PFNGLDISABLEPROC,glDisable) \
	EntryPoint(PFNGLDRAWARRAYSPROC,glDrawArrays) \
	EntryPoint(PFNGLDRAWBUFFERPROC,glDrawBuffer) \
	EntryPoint(PFNGLDRAWELEMENTSPROC,glDrawElements) \
	EntryPoint(PFNGLENABLEPROC,glEnable) \
	EntryPoint(PFNGLFINISHPROC,glFinish) \
	EntryPoint(PFNGLFLUSHPROC,glFlush) \
	EntryPoint(PFNGLFRONTFACEPROC,glFrontFace) \
	EntryPoint(PFNGLGENTEXTURESPROC,glGenTextures) \
	EntryPoint(PFNGLGETBOOLEANVPROC,glGetBooleanv) \
	EntryPoint(PFNGLGETDOUBLEVPROC,glGetDoublev) \
	EntryPoint(PFNGLGETERRORPROC,glGetError) \
	EntryPoint(PFNGLGETFLOATVPROC,glGetFloatv) \
	EntryPoint(PFNGLGETINTEGERVPROC,glGetIntegerv) \
	EntryPoint(PFNGLGETPOINTERVPROC,glGetPointerv) \
	EntryPoint(PFNGLGETSTRINGPROC,glGetString) \
	EntryPoint(PFNGLGETTEXIMAGEPROC,glGetTexImage) \
	EntryPoint(PFNGLGETTEXLEVELPARAMETERFVPROC,glGetTexLevelParameterfv) \
	EntryPoint(PFNGLGETTEXLEVELPARAMETERIVPROC,glGetTexLevelParameteriv) \
	EntryPoint(PFNGLGETTEXPARAMETERFVPROC,glGetTexParameterfv) \
	EntryPoint(PFNGLGETTEXPARAMETERIVPROC,glGetTexParameteriv) \
	EntryPoint(PFNGLHINTPROC,glHint) \
	EntryPoint(PFNGLISENABLEDPROC,glIsEnabled) \
	EntryPoint(PFNGLISTEXTUREPROC,glIsTexture) \
	EntryPoint(PFNGLLINEWIDTHPROC,glLineWidth) \
	EntryPoint(PFNGLLOGICOPPROC,glLogicOp) \
	EntryPoint(PFNGLPIXELSTOREFPROC,glPixelStoref) \
	EntryPoint(PFNGLPIXELSTOREIPROC,glPixelStorei) \
	EntryPoint(PFNGLPOINTSIZEPROC,glPointSize) \
	EntryPoint(PFNGLPOLYGONMODEPROC,glPolygonMode) \
	EntryPoint(PFNGLPOLYGONOFFSETPROC,glPolygonOffset) \
	EntryPoint(PFNGLREADBUFFERPROC,glReadBuffer) \
	EntryPoint(PFNGLREADPIXELSPROC,glReadPixels) \
	EntryPoint(PFNGLSCISSORPROC,glScissor) \
	EntryPoint(PFNGLCLEARDEPTHPROC,glClearDepth) \
	EntryPoint(PFNGLCLEARCOLORPROC,glClearColor) \
	EntryPoint(PFNGLCLEARSTENCILPROC,glClearStencil) \
	EntryPoint(PFNGLCLEARPROC,glClear) \
	EntryPoint(PFNGLSTENCILFUNCPROC,glStencilFunc) \
	EntryPoint(PFNGLSTENCILMASKPROC,glStencilMask) \
	EntryPoint(PFNGLSTENCILOPPROC,glStencilOp) \
	EntryPoint(PFNGLTEXIMAGE1DPROC,glTexImage1D) \
	EntryPoint(PFNGLTEXIMAGE2DPROC,glTexImage2D) \
	EntryPoint(PFNGLTEXPARAMETERFPROC,glTexParameterf) \
	EntryPoint(PFNGLTEXPARAMETERFVPROC,glTexParameterfv) \
	EntryPoint(PFNGLTEXPARAMETERIPROC,glTexParameteri) \
	EntryPoint(PFNGLTEXPARAMETERIVPROC,glTexParameteriv) \
	EntryPoint(PFNGLTEXSUBIMAGE1DPROC,glTexSubImage1D) \
	EntryPoint(PFNGLTEXSUBIMAGE2DPROC,glTexSubImage2D) \
	EntryPoint(PFNGLVIEWPORTPROC,glViewport) \

#define GL_ENTRYPOINTS(EntryPoint) \
	EntryPoint(PFNGLDEBUGMESSAGECALLBACKPROC, glDebugMessageCallback) \
	EntryPoint(PFNGLDEBUGMESSAGECONTROLPROC, glDebugMessageControl) \
	EntryPoint(PFNGLDRAWELEMENTSBASEVERTEXPROC,glDrawElementsBaseVertex) \
	EntryPoint(PFNGLCREATETEXTURESPROC,glCreateTextures) \
	EntryPoint(PFNGLTEXTURESTORAGE2DPROC,glTextureStorage2D) \
	EntryPoint(PFNGLTEXTURESUBIMAGE2DPROC,glTextureSubImage2D) \
	EntryPoint(PFNGLTEXTUREPARAMETERIPROC,glTextureParameteri) \
	EntryPoint(PFNGLBINDSAMPLERPROC,glBindSampler) \
	EntryPoint(PFNGLDELETESAMPLERSPROC,glDeleteSamplers) \
	EntryPoint(PFNGLGENSAMPLERSPROC,glGenSamplers) \
	EntryPoint(PFNGLSAMPLERPARAMETERIPROC,glSamplerParameteri) \
	EntryPoint(PFNGLCLEARBUFFERFVPROC,glClearBufferfv) \
	EntryPoint(PFNGLCLEARBUFFERIVPROC,glClearBufferiv) \
	EntryPoint(PFNGLCLEARBUFFERUIVPROC,glClearBufferuiv) \
	EntryPoint(PFNGLCLEARBUFFERFIPROC,glClearBufferfi) \
	EntryPoint(PFNGLCOLORMASKIPROC,glColorMaski) \
	EntryPoint(PFNGLDISABLEIPROC,glDisablei) \
	EntryPoint(PFNGLENABLEIPROC,glEnablei) \
	EntryPoint(PFNGLGETBOOLEANI_VPROC,glGetBooleani_v) \
	EntryPoint(PFNGLGETINTEGERI_VPROC,glGetIntegeri_v) \
	EntryPoint(PFNGLISENABLEDIPROC,glIsEnabledi) \
	EntryPoint(PFNGLBLENDCOLORPROC,glBlendColor) \
	EntryPoint(PFNGLBLENDEQUATIONPROC,glBlendEquation) \
	EntryPoint(PFNGLDRAWRANGEELEMENTSPROC,glDrawRangeElements) \
	EntryPoint(PFNGLTEXIMAGE3DPROC,glTexImage3D) \
	EntryPoint(PFNGLTEXSUBIMAGE3DPROC,glTexSubImage3D) \
	EntryPoint(PFNGLCOPYTEXSUBIMAGE3DPROC,glCopyTexSubImage3D) \
	EntryPoint(PFNGLACTIVETEXTUREPROC,glActiveTexture) \
	EntryPoint(PFNGLSAMPLECOVERAGEPROC,glSampleCoverage) \
	EntryPoint(PFNGLCOMPRESSEDTEXIMAGE3DPROC,glCompressedTexImage3D) \
	EntryPoint(PFNGLCOMPRESSEDTEXIMAGE2DPROC,glCompressedTexImage2D) \
	EntryPoint(PFNGLCOMPRESSEDTEXIMAGE1DPROC,glCompressedTexImage1D) \
	EntryPoint(PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC,glCompressedTexSubImage3D) \
	EntryPoint(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC,glCompressedTexSubImage2D) \
	EntryPoint(PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC,glCompressedTexSubImage1D) \
	EntryPoint(PFNGLGETCOMPRESSEDTEXIMAGEPROC,glGetCompressedTexImage) \
	EntryPoint(PFNGLBLENDFUNCSEPARATEPROC,glBlendFuncSeparate) \
	EntryPoint(PFNGLMULTIDRAWARRAYSPROC,glMultiDrawArrays) \
	EntryPoint(PFNGLMULTIDRAWELEMENTSPROC,glMultiDrawElements) \
	EntryPoint(PFNGLPOINTPARAMETERFPROC,glPointParameterf) \
	EntryPoint(PFNGLPOINTPARAMETERFVPROC,glPointParameterfv) \
	EntryPoint(PFNGLPOINTPARAMETERIPROC,glPointParameteri) \
	EntryPoint(PFNGLPOINTPARAMETERIVPROC,glPointParameteriv) \
	EntryPoint(PFNGLGENQUERIESPROC,glGenQueries) \
	EntryPoint(PFNGLDELETEQUERIESPROC,glDeleteQueries) \
	EntryPoint(PFNGLISQUERYPROC,glIsQuery) \
	EntryPoint(PFNGLBEGINQUERYPROC,glBeginQuery) \
	EntryPoint(PFNGLENDQUERYPROC,glEndQuery) \
	EntryPoint(PFNGLGETQUERYIVPROC,glGetQueryiv) \
	EntryPoint(PFNGLGETQUERYOBJECTIVPROC,glGetQueryObjectiv) \
	EntryPoint(PFNGLGETQUERYOBJECTUIVPROC,glGetQueryObjectuiv) \
	EntryPoint(PFNGLBINDBUFFERPROC,glBindBuffer) \
	EntryPoint(PFNGLBINDBUFFERBASEPROC,glBindBufferBase) \
	EntryPoint(PFNGLDELETEBUFFERSPROC,glDeleteBuffers) \
	EntryPoint(PFNGLCREATEBUFFERSPROC, glCreateBuffers) \
	EntryPoint(PFNGLNAMEDBUFFERSTORAGEPROC, glNamedBufferStorage) \
	EntryPoint(PFNGLBINDVERTEXBUFFERPROC, glBindVertexBuffer) \
	EntryPoint(PFNGLMAPNAMEDBUFFERRANGEPROC, glMapNamedBufferRange) \
	EntryPoint(PFNGLUNMAPNAMEDBUFFERPROC, glUnmapNamedBuffer) \
	EntryPoint(PFNGLISBUFFERPROC,glIsBuffer) \
	EntryPoint(PFNGLBUFFERDATAPROC,glBufferData) \
	EntryPoint(PFNGLBUFFERSUBDATAPROC,glBufferSubData) \
	EntryPoint(PFNGLGETBUFFERSUBDATAPROC,glGetBufferSubData) \
	EntryPoint(PFNGLMAPBUFFERPROC,glMapBuffer) \
	EntryPoint(PFNGLUNMAPBUFFERPROC,glUnmapBuffer) \
	EntryPoint(PFNGLGETBUFFERPARAMETERIVPROC,glGetBufferParameteriv) \
	EntryPoint(PFNGLGETBUFFERPOINTERVPROC,glGetBufferPointerv) \
	EntryPoint(PFNGLBLENDEQUATIONSEPARATEPROC,glBlendEquationSeparate) \
	EntryPoint(PFNGLDRAWBUFFERSPROC,glDrawBuffers) \
	EntryPoint(PFNGLSTENCILOPSEPARATEPROC,glStencilOpSeparate) \
	EntryPoint(PFNGLSTENCILFUNCSEPARATEPROC,glStencilFuncSeparate) \
	EntryPoint(PFNGLSTENCILMASKSEPARATEPROC,glStencilMaskSeparate) \
	EntryPoint(PFNGLATTACHSHADERPROC,glAttachShader) \
	EntryPoint(PFNGLBINDATTRIBLOCATIONPROC,glBindAttribLocation) \
	EntryPoint(PFNGLBINDFRAGDATALOCATIONPROC,glBindFragDataLocation) \
	EntryPoint(PFNGLCOMPILESHADERPROC,glCompileShader) \
	EntryPoint(PFNGLCREATEPROGRAMPROC,glCreateProgram) \
	EntryPoint(PFNGLCREATESHADERPROC,glCreateShader) \
	EntryPoint(PFNGLDELETEPROGRAMPROC,glDeleteProgram) \
	EntryPoint(PFNGLDELETESHADERPROC,glDeleteShader) \
	EntryPoint(PFNGLDETACHSHADERPROC,glDetachShader) \
	EntryPoint(PFNGLDISABLEVERTEXATTRIBARRAYPROC,glDisableVertexAttribArray) \
	EntryPoint(PFNGLENABLEVERTEXATTRIBARRAYPROC,glEnableVertexAttribArray) \
	EntryPoint(PFNGLGETACTIVEATTRIBPROC,glGetActiveAttrib) \
	EntryPoint(PFNGLGETACTIVEUNIFORMPROC,glGetActiveUniform) \
	EntryPoint(PFNGLGETATTACHEDSHADERSPROC,glGetAttachedShaders) \
	EntryPoint(PFNGLGETATTRIBLOCATIONPROC,glGetAttribLocation) \
	EntryPoint(PFNGLGETPROGRAMIVPROC,glGetProgramiv) \
	EntryPoint(PFNGLGETPROGRAMINFOLOGPROC,glGetProgramInfoLog) \
	EntryPoint(PFNGLGETSHADERIVPROC,glGetShaderiv) \
	EntryPoint(PFNGLGETSHADERINFOLOGPROC,glGetShaderInfoLog) \
	EntryPoint(PFNGLGETSHADERSOURCEPROC,glGetShaderSource) \
	EntryPoint(PFNGLGETUNIFORMLOCATIONPROC,glGetUniformLocation) \
	EntryPoint(PFNGLGETUNIFORMBLOCKINDEXPROC,glGetUniformBlockIndex) \
	EntryPoint(PFNGLGETUNIFORMFVPROC,glGetUniformfv) \
	EntryPoint(PFNGLGETUNIFORMIVPROC,glGetUniformiv) \
	EntryPoint(PFNGLGETVERTEXATTRIBDVPROC,glGetVertexAttribdv) \
	EntryPoint(PFNGLGETVERTEXATTRIBFVPROC,glGetVertexAttribfv) \
	EntryPoint(PFNGLGETVERTEXATTRIBIVPROC,glGetVertexAttribiv) \
	EntryPoint(PFNGLGETVERTEXATTRIBPOINTERVPROC,glGetVertexAttribPointerv) \
	EntryPoint(PFNGLISPROGRAMPROC,glIsProgram) \
	EntryPoint(PFNGLISSHADERPROC,glIsShader) \
	EntryPoint(PFNGLLINKPROGRAMPROC,glLinkProgram) \
	EntryPoint(PFNGLSHADERSOURCEPROC,glShaderSource) \
	EntryPoint(PFNGLUSEPROGRAMPROC,glUseProgram) \
	EntryPoint(PFNGLUNIFORM1FPROC,glUniform1f) \
	EntryPoint(PFNGLUNIFORM2FPROC,glUniform2f) \
	EntryPoint(PFNGLUNIFORM3FPROC,glUniform3f) \
	EntryPoint(PFNGLUNIFORM4FPROC,glUniform4f) \
	EntryPoint(PFNGLUNIFORM1IPROC,glUniform1i) \
	EntryPoint(PFNGLUNIFORM2IPROC,glUniform2i) \
	EntryPoint(PFNGLUNIFORM3IPROC,glUniform3i) \
	EntryPoint(PFNGLUNIFORM4IPROC,glUniform4i) \
	EntryPoint(PFNGLUNIFORM1FVPROC,glUniform1fv) \
	EntryPoint(PFNGLUNIFORM2FVPROC,glUniform2fv) \
	EntryPoint(PFNGLUNIFORM3FVPROC,glUniform3fv) \
	EntryPoint(PFNGLUNIFORM4FVPROC,glUniform4fv) \
	EntryPoint(PFNGLUNIFORM1IVPROC,glUniform1iv) \
	EntryPoint(PFNGLUNIFORM2IVPROC,glUniform2iv) \
	EntryPoint(PFNGLUNIFORM3IVPROC,glUniform3iv) \
	EntryPoint(PFNGLUNIFORM4IVPROC,glUniform4iv) \
	EntryPoint(PFNGLUNIFORM1UIVPROC,glUniform1uiv) \
	EntryPoint(PFNGLUNIFORM2UIVPROC,glUniform2uiv) \
	EntryPoint(PFNGLUNIFORM3UIVPROC,glUniform3uiv) \
	EntryPoint(PFNGLUNIFORM4UIVPROC,glUniform4uiv) \
	EntryPoint(PFNGLUNIFORMBLOCKBINDINGPROC,glUniformBlockBinding) \
	EntryPoint(PFNGLUNIFORMMATRIX2FVPROC,glUniformMatrix2fv) \
	EntryPoint(PFNGLUNIFORMMATRIX3FVPROC,glUniformMatrix3fv) \
	EntryPoint(PFNGLUNIFORMMATRIX4FVPROC,glUniformMatrix4fv) \
	EntryPoint(PFNGLVALIDATEPROGRAMPROC,glValidateProgram) \
	EntryPoint(PFNGLVERTEXATTRIB1DPROC,glVertexAttrib1d) \
	EntryPoint(PFNGLVERTEXATTRIB1DVPROC,glVertexAttrib1dv) \
	EntryPoint(PFNGLVERTEXATTRIB1FPROC,glVertexAttrib1f) \
	EntryPoint(PFNGLVERTEXATTRIB1FVPROC,glVertexAttrib1fv) \
	EntryPoint(PFNGLVERTEXATTRIB1SPROC,glVertexAttrib1s) \
	EntryPoint(PFNGLVERTEXATTRIB1SVPROC,glVertexAttrib1sv) \
	EntryPoint(PFNGLVERTEXATTRIB2DPROC,glVertexAttrib2d) \
	EntryPoint(PFNGLVERTEXATTRIB2DVPROC,glVertexAttrib2dv) \
	EntryPoint(PFNGLVERTEXATTRIB2FPROC,glVertexAttrib2f) \
	EntryPoint(PFNGLVERTEXATTRIB2FVPROC,glVertexAttrib2fv) \
	EntryPoint(PFNGLVERTEXATTRIB2SPROC,glVertexAttrib2s) \
	EntryPoint(PFNGLVERTEXATTRIB2SVPROC,glVertexAttrib2sv) \
	EntryPoint(PFNGLVERTEXATTRIB3DPROC,glVertexAttrib3d) \
	EntryPoint(PFNGLVERTEXATTRIB3DVPROC,glVertexAttrib3dv) \
	EntryPoint(PFNGLVERTEXATTRIB3FPROC,glVertexAttrib3f) \
	EntryPoint(PFNGLVERTEXATTRIB3FVPROC,glVertexAttrib3fv) \
	EntryPoint(PFNGLVERTEXATTRIB3SPROC,glVertexAttrib3s) \
	EntryPoint(PFNGLVERTEXATTRIB3SVPROC,glVertexAttrib3sv) \
	EntryPoint(PFNGLVERTEXATTRIB4NBVPROC,glVertexAttrib4Nbv) \
	EntryPoint(PFNGLVERTEXATTRIB4NIVPROC,glVertexAttrib4Niv) \
	EntryPoint(PFNGLVERTEXATTRIB4NSVPROC,glVertexAttrib4Nsv) \
	EntryPoint(PFNGLVERTEXATTRIB4NUBPROC,glVertexAttrib4Nub) \
	EntryPoint(PFNGLVERTEXATTRIB4NUBVPROC,glVertexAttrib4Nubv) \
	EntryPoint(PFNGLVERTEXATTRIB4NUIVPROC,glVertexAttrib4Nuiv) \
	EntryPoint(PFNGLVERTEXATTRIB4NUSVPROC,glVertexAttrib4Nusv) \
	EntryPoint(PFNGLVERTEXATTRIB4BVPROC,glVertexAttrib4bv) \
	EntryPoint(PFNGLVERTEXATTRIB4DPROC,glVertexAttrib4d) \
	EntryPoint(PFNGLVERTEXATTRIB4DVPROC,glVertexAttrib4dv) \
	EntryPoint(PFNGLVERTEXATTRIB4FPROC,glVertexAttrib4f) \
	EntryPoint(PFNGLVERTEXATTRIB4FVPROC,glVertexAttrib4fv) \
	EntryPoint(PFNGLVERTEXATTRIB4IVPROC,glVertexAttrib4iv) \
	EntryPoint(PFNGLVERTEXATTRIB4SPROC,glVertexAttrib4s) \
	EntryPoint(PFNGLVERTEXATTRIB4SVPROC,glVertexAttrib4sv) \
	EntryPoint(PFNGLVERTEXATTRIB4UBVPROC,glVertexAttrib4ubv) \
	EntryPoint(PFNGLVERTEXATTRIB4UIVPROC,glVertexAttrib4uiv) \
	EntryPoint(PFNGLVERTEXATTRIB4USVPROC,glVertexAttrib4usv) \
	EntryPoint(PFNGLVERTEXATTRIBI4IVPROC,glVertexAttribI4iv) \
	EntryPoint(PFNGLVERTEXATTRIBI4UIVPROC,glVertexAttribI4uiv) \
	EntryPoint(PFNGLVERTEXATTRIBI4SVPROC,glVertexAttribI4sv) \
	EntryPoint(PFNGLVERTEXATTRIBI4USVPROC,glVertexAttribI4usv) \
	EntryPoint(PFNGLVERTEXATTRIBI4BVPROC,glVertexAttribI4bv) \
	EntryPoint(PFNGLVERTEXATTRIBI4UBVPROC,glVertexAttribI4ubv) \
	EntryPoint(PFNGLVERTEXATTRIBPOINTERPROC,glVertexAttribPointer) \
	EntryPoint(PFNGLVERTEXATTRIBIPOINTERPROC,glVertexAttribIPointer) \
	EntryPoint(PFNGLUNIFORMMATRIX2X3FVPROC,glUniformMatrix2x3fv) \
	EntryPoint(PFNGLUNIFORMMATRIX3X2FVPROC,glUniformMatrix3x2fv) \
	EntryPoint(PFNGLUNIFORMMATRIX2X4FVPROC,glUniformMatrix2x4fv) \
	EntryPoint(PFNGLUNIFORMMATRIX4X2FVPROC,glUniformMatrix4x2fv) \
	EntryPoint(PFNGLUNIFORMMATRIX3X4FVPROC,glUniformMatrix3x4fv) \
	EntryPoint(PFNGLUNIFORMMATRIX4X3FVPROC,glUniformMatrix4x3fv) \
	EntryPoint(PFNGLISRENDERBUFFERPROC,glIsRenderbuffer) \
	EntryPoint(PFNGLBINDRENDERBUFFERPROC,glBindRenderbuffer) \
	EntryPoint(PFNGLDELETERENDERBUFFERSPROC,glDeleteRenderbuffers) \
	EntryPoint(PFNGLGENRENDERBUFFERSPROC,glGenRenderbuffers) \
	EntryPoint(PFNGLRENDERBUFFERSTORAGEPROC,glRenderbufferStorage) \
	EntryPoint(PFNGLGETRENDERBUFFERPARAMETERIVPROC,glGetRenderbufferParameteriv) \
	EntryPoint(PFNGLISFRAMEBUFFERPROC,glIsFramebuffer) \
	EntryPoint(PFNGLBINDFRAMEBUFFERPROC,glBindFramebuffer) \
	EntryPoint(PFNGLDELETEFRAMEBUFFERSPROC,glDeleteFramebuffers) \
	EntryPoint(PFNGLGENFRAMEBUFFERSPROC,glGenFramebuffers) \
	EntryPoint(PFNGLCHECKFRAMEBUFFERSTATUSPROC,glCheckFramebufferStatus) \
	EntryPoint(PFNGLFRAMEBUFFERTEXTURE1DPROC,glFramebufferTexture1D) \
	EntryPoint(PFNGLFRAMEBUFFERTEXTURE2DPROC,glFramebufferTexture2D) \
	EntryPoint(PFNGLFRAMEBUFFERTEXTURE3DPROC,glFramebufferTexture3D) \
	EntryPoint(PFNGLFRAMEBUFFERTEXTUREPROC,glFramebufferTexture) \
	EntryPoint(PFNGLFRAMEBUFFERRENDERBUFFERPROC,glFramebufferRenderbuffer) \
	EntryPoint(PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC,glGetFramebufferAttachmentParameteriv) \
	EntryPoint(PFNGLGENERATEMIPMAPPROC,glGenerateMipmap) \
	EntryPoint(PFNGLBLITFRAMEBUFFERPROC,glBlitFramebuffer) \
	EntryPoint(PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC,glRenderbufferStorageMultisample) \
	EntryPoint(PFNGLFRAMEBUFFERTEXTURELAYERPROC,glFramebufferTextureLayer) \
	EntryPoint(PFNGLMAPBUFFERRANGEPROC,glMapBufferRange) \
	EntryPoint(PFNGLFLUSHMAPPEDBUFFERRANGEPROC,glFlushMappedBufferRange) \
	EntryPoint(PFNGLVERTEXATTRIBDIVISORPROC,glVertexAttribDivisor) \
	EntryPoint(PFNGLDRAWARRAYSINSTANCEDPROC,glDrawArraysInstanced) \
	EntryPoint(PFNGLDRAWELEMENTSINSTANCEDPROC,glDrawElementsInstanced) \
	EntryPoint(PFNGLGETSTRINGIPROC,glGetStringi) \
	EntryPoint(PFNGLGENVERTEXARRAYSPROC,glGenVertexArrays) \
	EntryPoint(PFNGLDELETEVERTEXARRAYSPROC,glDeleteVertexArrays) \
	EntryPoint(PFNGLBINDVERTEXARRAYPROC,glBindVertexArray) \
	EntryPoint(PFNGLCOPYBUFFERSUBDATAPROC,glCopyBufferSubData) \
	EntryPoint(PFNGLTEXBUFFERPROC,glTexBuffer) \
	EntryPoint(PFNGLTEXIMAGE2DMULTISAMPLEPROC,glTexImage2DMultisample) \
	EntryPoint(PFNGLQUERYCOUNTERPROC, glQueryCounter)\
	EntryPoint(PFNGLISSYNCPROC, glIsSync)\
	EntryPoint(PFNGLDELETESYNCPROC, glDeleteSync)\
	EntryPoint(PFNGLGETQUERYOBJECTUI64VPROC, glGetQueryObjectui64v)\
	EntryPoint(PFNGLFENCESYNCPROC, glFenceSync)\
	EntryPoint(PFNGLGETSYNCIVPROC, glGetSynciv)\
	EntryPoint(PFNGLCLIENTWAITSYNCPROC, glClientWaitSync)\
	EntryPoint(PFNGLBINDBUFFERRANGEPROC, glBindBufferRange)\
	EntryPoint(PFNGLBINDTEXTUREUNITPROC,glBindTextureUnit)

#define GL_ENTRYPOINTS_ALL(EntryPoint) \
	GL_ENTRYPOINTS_DLL(EntryPoint) \
	GL_ENTRYPOINTS(EntryPoint)

#define DECLARE_GL_ENTRYPOINTS(Type,Func) extern Type Func;
GL_ENTRYPOINTS_ALL(DECLARE_GL_ENTRYPOINTS);
#undef DECLARE_GL_ENTRYPOINTS

extern PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;

#endif